_target_: src.models.imcap_module.IMCAPLitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.00005
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: transformers.AutoModelForVision2Seq.from_pretrained
  pretrained_model_name_or_path: microsoft/git-base
  cache_dir: models/huggingface

processor:
  _target_: transformers.AutoProcessor.from_pretrained
  pretrained_model_name_or_path: microsoft/git-base
  cache_dir: models/huggingface

# compile model for faster training with pytorch 2.0
compile: false

# HuggingFace repo ID to push model
hf_repo_id: null
